"""Deterministic task evolution controller."""

from __future__ import annotations

from dataclasses import replace
from typing import Any

from leo_twin.sees.task_dag import (
    TASK_SPLIT,
    EngineeringTask,
    TaskDAG,
)


class EvolutionController:
    """Rewrite failed tasks into smaller deterministic subtasks."""

    def split_failed_task(
        self,
        task: EngineeringTask,
        report: dict[str, Any],
    ) -> tuple[EngineeringTask, ...]:
        fix_sources = report.get("required_fixes") or report.get("violations") or [
            "Re-run deterministic review and isolate remaining failure."
        ]
        subtasks: list[EngineeringTask] = []
        previous_dependency: str | None = None

        for index, fix in enumerate(fix_sources, start=1):
            task_id = f"{task.task_id}.fix{index:02d}"
            dependencies = (
                (previous_dependency,)
                if previous_dependency is not None
                else task.dependencies
            )
            subtasks.append(
                EngineeringTask(
                    task_id=task_id,
                    title=f"{task.title}: fix {index}",
                    description=str(fix),
                    issue_id=f"{task.issue_id}-FIX{index:02d}",
                    dependencies=dependencies,
                )
            )
            previous_dependency = task_id
        return tuple(subtasks)

    def evolve_failed_task(
        self,
        dag: TaskDAG,
        task_id: str,
        report: dict[str, Any],
    ) -> tuple[EngineeringTask, ...]:
        original = dag.get_task(task_id)
        subtasks = self.split_failed_task(original, report)
        dag.mark_status(task_id, TASK_SPLIT)
        for subtask in subtasks:
            dag.add_task(subtask)
        if subtasks:
            dag.replace_dependency(task_id, subtasks[-1].task_id)
        return subtasks

    def generate_next_task(
        self,
        dag: TaskDAG,
        title: str = "Generate next deterministic engineering task",
    ) -> EngineeringTask:
        completed = [
            task.task_id
            for task in dag.tasks()
            if task.status in {"complete", "split"}
        ]
        task_number = len(dag.tasks()) + 1
        return EngineeringTask(
            task_id=f"task-auto-{task_number:03d}",
            title=title,
            description="Generated by EvolutionController after a deterministic loop.",
            issue_id=f"AUTO-{task_number:03d}",
            dependencies=tuple(sorted(completed)),
        )


def clone_task_with_patch_plan(
    task: EngineeringTask,
    patch_plan: tuple[Any, ...],
) -> EngineeringTask:
    return replace(task, patch_plan=patch_plan)
