"""Backend-owned user configuration surface summaries."""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from leo_twin.schema.config import SEESConfig, config_to_dict
from leo_twin.schema.config_loader import ConfigValidationError, load_config
from leo_twin.services.configuration_schema import (
    USER_CONFIGURATION_SCHEMA_V2_ID,
    build_user_configuration_schema_v2,
    validate_user_configuration_mapping_v2,
)
from leo_twin.services.runtime_reproducibility import stable_hash_payload


ConfigurationView = dict[str, object]
UserConfigurationReference = dict[str, object]
UserConfigurationTemplateValidation = dict[str, object]

_KEY_FIELD_PATHS = (
    "scenario.satellite_count",
    "scenario.user_count",
    "scenario.compute_nodes",
    "scenario.compute_capacity",
    "scenario.compute_gpu_tflops_fp32",
    "scenario.compute_npu_tops_int8",
    "scenario.orbit.update_interval_seconds",
    "scenario.orbit.plane_count",
    "scenario.orbit.altitude_m",
    "scenario.orbit.inclination_deg",
    "scenario.traffic_model.traffic_class",
    "scenario.traffic_model.destination_type",
    "scenario.traffic_model.flow_interval_seconds",
    "scenario.traffic_model.task_interval_seconds",
    "scenario.traffic_model.flow_demand_capacity",
    "scenario.traffic_model.task_compute_demand",
    "scenario.traffic_model.task_data_size",
    "scenario.traffic_model.output_data_size",
    "network.application_protocol",
    "network.transport_protocol",
    "network.transport_loss_rate",
    "network.transport_congestion_window_segments",
    "network.routing_protocol",
    "network.datalink_mac_protocol",
    "network.space_link_mode",
    "runtime.mode",
    "runtime.speed_factor",
    "runtime.seed",
    "runtime.duration",
)

_FIELD_METADATA: Mapping[str, Mapping[str, str]] = {
    "scenario.satellite_count": {
        "label": "Satellite count",
        "section": "Scenario scale",
        "role": "Primary constellation size selected by the user.",
    },
    "scenario.user_count": {
        "label": "User node count",
        "section": "Scenario scale",
        "role": "Number of generated user terminals.",
    },
    "scenario.compute_nodes": {
        "label": "Compute satellite count",
        "section": "Scenario scale",
        "role": "Satellites that host compute resources.",
    },
    "scenario.compute_capacity": {
        "label": "CPU FP32 per compute satellite",
        "section": "Compute resources",
        "role": "Legacy scalar capacity mapped to FP32 GFLOPS.",
        "unit": "GFLOPS",
    },
    "scenario.compute_gpu_tflops_fp32": {
        "label": "GPU FP32 per compute satellite",
        "section": "Compute resources",
        "role": "Optional accelerator capacity.",
        "unit": "TFLOPS",
    },
    "scenario.compute_npu_tops_int8": {
        "label": "NPU INT8 per compute satellite",
        "section": "Compute resources",
        "role": "Optional inference accelerator capacity.",
        "unit": "TOPS",
    },
    "scenario.orbit.plane_count": {
        "label": "Orbit plane count",
        "section": "Orbit",
        "role": "Walker-like deterministic plane allocation input.",
    },
    "scenario.orbit.update_interval_seconds": {
        "label": "Orbit update interval",
        "section": "Orbit",
        "role": "Deterministic orbit sampling interval.",
        "unit": "s",
    },
    "scenario.orbit.altitude_m": {
        "label": "Orbit altitude",
        "section": "Orbit",
        "role": "Simplified circular orbit altitude.",
        "unit": "m",
    },
    "scenario.orbit.inclination_deg": {
        "label": "Inclination",
        "section": "Orbit",
        "role": "Simplified orbit inclination.",
        "unit": "deg",
    },
    "scenario.traffic_model.traffic_class": {
        "label": "Traffic class",
        "section": "Traffic demand",
        "role": "Flow-level demand class generated by the backend.",
    },
    "scenario.traffic_model.destination_type": {
        "label": "Traffic destination type",
        "section": "Traffic demand",
        "role": "Backend destination category for generated flows.",
    },
    "scenario.traffic_model.flow_interval_seconds": {
        "label": "Flow arrival interval",
        "section": "Traffic demand",
        "role": "Deterministic interval between generated flow arrivals.",
        "unit": "s",
    },
    "scenario.traffic_model.task_interval_seconds": {
        "label": "Task arrival interval",
        "section": "Traffic demand",
        "role": "Deterministic interval between generated compute-service tasks.",
        "unit": "s",
    },
    "scenario.traffic_model.flow_demand_capacity": {
        "label": "Flow demand",
        "section": "Traffic demand",
        "role": "Requested flow capacity.",
        "unit": "Mbps",
    },
    "scenario.traffic_model.task_compute_demand": {
        "label": "Task compute demand",
        "section": "Traffic demand",
        "role": "Abstract compute demand for compute-service tasks.",
    },
    "scenario.traffic_model.task_data_size": {
        "label": "Input data size",
        "section": "Traffic demand",
        "role": "Input data volume used by generated task or flow requests.",
        "unit": "MB",
    },
    "scenario.traffic_model.output_data_size": {
        "label": "Output data size",
        "section": "Traffic demand",
        "role": "Result data volume metadata for compute-service flows.",
        "unit": "MB",
    },
    "network.application_protocol": {
        "label": "Application protocol",
        "section": "Network",
        "role": "Flow-level application profile.",
    },
    "network.transport_protocol": {
        "label": "Transport protocol",
        "section": "Network",
        "role": "Flow-level transport profile.",
    },
    "network.transport_loss_rate": {
        "label": "Transport loss rate",
        "section": "Network",
        "role": "Deterministic loss proxy input, not packet loss simulation.",
    },
    "network.transport_congestion_window_segments": {
        "label": "Congestion window",
        "section": "Network",
        "role": "Flow-level transport congestion-window constraint.",
    },
    "network.routing_protocol": {
        "label": "Routing protocol",
        "section": "Network",
        "role": "Flow-level route selection profile.",
    },
    "network.datalink_mac_protocol": {
        "label": "Data-link MAC protocol",
        "section": "Network",
        "role": "Flow-level data-link runtime profile.",
    },
    "network.space_link_mode": {
        "label": "Space-space link mode",
        "section": "Network",
        "role": "Selected ISL fidelity mode.",
    },
    "runtime.mode": {
        "label": "Runtime mode",
        "section": "Runtime",
        "role": "Execution mode selected before start.",
    },
    "runtime.speed_factor": {
        "label": "Runtime speed",
        "section": "Runtime",
        "role": "Acceleration factor, locked while running.",
    },
    "runtime.seed": {
        "label": "Deterministic seed",
        "section": "Runtime",
        "role": "Seed for deterministic scenario generation.",
    },
    "runtime.duration": {
        "label": "Simulation duration",
        "section": "Runtime",
        "role": "Configured terminal simulation time.",
        "unit": "s",
    },
}

_SECTION_PURPOSES = {
    "scenario": "Constellation scale, compute resource, workload, orbit, and traffic demand.",
    "scenario.orbit": "Deterministic orbit allocation and update cadence.",
    "scenario.traffic_model": "Flow-level user business generation model.",
    "network": "Flow-level protocol, link budget, routing, and ISL fidelity inputs.",
    "runtime": "Execution mode, speed, seed, and duration.",
    "ui": "Frontend visualization preferences.",
    "ui.visualization": "Layer visibility defaults.",
}

_TEMPLATE_PROFILES = (
    {
        "id": "baseline_72sat",
        "label": "72-satellite baseline",
        "path": "configs/templates/sees_user_detailed.example.yaml",
        "purpose": "Executable baseline for full-contract editing.",
        "scale": "72 satellites, 72 compute nodes, baseline user demand.",
        "expected_kpi_behavior": (
            "Stable low-to-medium pressure KPI curves for validating the full "
            "configuration contract."
        ),
        "fidelity_mode": "SMALL_SCALE_PER_SATELLITE_ORBIT",
        "recommended_use": "Start here for deterministic smoke tests and full YAML editing.",
    },
    {
        "id": "dynamic_observability_120sat",
        "label": "120-satellite dynamic observability",
        "path": "configs/templates/sees_user_dynamic_observability.example.yaml",
        "purpose": (
            "Mixed traffic, non-zero network proxies, and per-satellite compute "
            "resources for dashboard validation."
        ),
        "scale": "120 satellites, 120 compute nodes, mixed communication/compute demand.",
        "expected_kpi_behavior": (
            "Visible time-varying throughput, latency, loss proxy, jitter proxy, "
            "and compute resource movement."
        ),
        "fidelity_mode": "MEDIUM_SCALE_DYNAMIC_OBSERVABILITY",
        "recommended_use": "Use for dashboard data-panel validation and operator demos.",
    },
    {
        "id": "network_stress_120sat",
        "label": "120-satellite network stress observability",
        "path": "configs/templates/sees_user_network_stress_120.example.yaml",
        "purpose": (
            "Higher flow-level demand, loss, rain, and routing pressure for "
            "validating changing network KPI curves."
        ),
        "scale": "120 satellites with elevated user demand and network pressure.",
        "expected_kpi_behavior": (
            "Non-zero loss and jitter proxies with route pressure and recent-flow "
            "KPI variation."
        ),
        "fidelity_mode": "MEDIUM_SCALE_NETWORK_STRESS",
        "recommended_use": "Use when checking KPI provenance, congestion, and stress behavior.",
    },
    {
        "id": "large_scale_1200sat",
        "label": "1200-satellite scale mode",
        "path": "configs/templates/sees_user_large_scale_1200.example.yaml",
        "purpose": (
            "Scale-safe batch orbit and bounded ISL template for large "
            "interactive scenarios."
        ),
        "scale": "1200 satellites with batched orbit updates and bounded ISL candidates.",
        "expected_kpi_behavior": (
            "Aggregated large-scale metrics with explicit fidelity degradation "
            "and bounded detail windows."
        ),
        "fidelity_mode": "LARGE_SCALE_BATCH_ORBIT_BOUNDED_ISL",
        "recommended_use": "Use for 1200-node responsiveness and scale-fidelity checks.",
    },
)

_REPOSITORY_ROOT = Path(__file__).resolve().parents[3]


def configuration_template_profiles() -> tuple[dict[str, str], ...]:
    """Return deterministic backend-approved user config template profiles."""

    return tuple(dict(profile) for profile in _TEMPLATE_PROFILES)


def build_user_configuration_template_validation_evidence(
    *,
    repository_root: Path | str | None = None,
) -> UserConfigurationTemplateValidation:
    """Return deterministic validation evidence for all approved config templates."""

    root = _REPOSITORY_ROOT if repository_root is None else Path(repository_root)
    rows = tuple(
        _template_validation_row(profile, root)
        for profile in configuration_template_profiles()
    )
    valid_count = sum(1 for row in rows if row["validation_ok"] is True)
    result: UserConfigurationTemplateValidation = {
        "version": "v1",
        "evidence_id": "sees.user_configuration_template_validation.v1",
        "source": "BACKEND_USER_CONFIGURATION",
        "schema_id": USER_CONFIGURATION_SCHEMA_V2_ID,
        "validation_scope": "APPROVED_EXECUTABLE_TEMPLATES",
        "template_count": len(rows),
        "valid_template_count": valid_count,
        "invalid_template_count": len(rows) - valid_count,
        "all_templates_valid": valid_count == len(rows),
        "templates": rows,
        "model_boundaries": {
            "event_kernel_policy": "NO_EVENT_KERNEL_BEHAVIOR_CHANGE",
            "packet_level_simulation": False,
            "external_simulators": False,
            "forbidden_integrations": ("STK", "EXATA", "AFSIM", "DDS"),
        },
        "notes": (
            "Template validation loads approved YAML files through the same backend config loader used by runtime control.",
            "The evidence hashes executable file content and normalized effective config without applying it to the running session.",
            "This is a read-only configuration product check and does not mutate runtime state.",
        ),
    }
    result["evidence_hash"] = stable_hash_payload(result)
    return result


def load_user_configuration_template(template_id: str) -> SEESConfig:
    """Load one backend-approved user configuration template by profile id."""

    if not isinstance(template_id, str) or not template_id:
        raise ConfigValidationError("template_id must be a non-empty string")
    profile = _template_profile_by_id(template_id)
    return load_config(_REPOSITORY_ROOT / str(profile["path"]))


def build_user_configuration_view(config: SEESConfig) -> ConfigurationView:
    """Return a deterministic user-facing config surface contract."""

    if not isinstance(config, SEESConfig):
        raise TypeError("config must be SEESConfig")
    data = config_to_dict(config)
    flattened = _flatten_paths(data)
    key_paths = tuple(path for path in _KEY_FIELD_PATHS if path in flattened)
    key_path_set = frozenset(key_paths)
    file_only_fields = tuple(path for path in flattened if path not in key_path_set)
    return {
        "version": "v1",
        "schema_version": "v2",
        "schema_id": "sees.user_configuration.v2",
        "source": "backend_sees_config",
        "detailed_config_file": "configs/sees_control.yaml",
        "template_config_file": "configs/templates/sees_user_detailed.example.yaml",
        "template_profiles": _TEMPLATE_PROFILES,
        "template_validation": build_user_configuration_template_validation_evidence(),
        "frontend_policy": "CONTROL_PANEL_KEY_FIELDS_ONLY",
        "key_field_count": len(key_paths),
        "detailed_field_count": len(flattened),
        "key_fields": tuple(
            _key_field(path, flattened[path])
            for path in key_paths
        ),
        "detailed_file_sections": tuple(
            _section_summary(section, flattened)
            for section in sorted(_SECTION_PURPOSES)
        ),
        "file_only_sections": _file_only_section_summaries(file_only_fields),
        "file_only_fields": file_only_fields,
        "user_config_schema_v2": build_user_configuration_schema_v2(config),
        "notes": (
            "The control panel should expose key_fields for common operation.",
            "Advanced users should edit the detailed config file or template for full control.",
            "This summary is derived from SEESConfig and is the backend source of truth.",
        ),
    }


def build_user_configuration_reference(
    config: SEESConfig,
    *,
    detailed_config_file: str = "configs/sees_control.yaml",
    generated_config_file: str = "configs/generated_full_system_demo.json",
) -> UserConfigurationReference:
    """Return the backend-owned full user configuration reference package."""

    if not isinstance(config, SEESConfig):
        raise TypeError("config must be SEESConfig")
    schema = build_user_configuration_schema_v2(config)
    view = build_user_configuration_view(config)
    fields = tuple(
        field for field in schema["fields"] if isinstance(field, Mapping)
    )
    key_field_paths = tuple(str(field["path"]) for field in view["key_fields"])
    key_field_set = frozenset(key_field_paths)
    sections = tuple(
        _reference_section(section, fields, key_field_set)
        for section in sorted(_SECTION_PURPOSES)
    )
    reference: UserConfigurationReference = {
        "version": "v1",
        "reference_id": "sees.user_configuration_reference.v1",
        "source": "BACKEND_USER_CONFIGURATION",
        "schema_id": USER_CONFIGURATION_SCHEMA_V2_ID,
        "reference_scope": "FULL_USER_CONFIGURATION_FILE_AND_FRONTEND_SURFACE",
        "format": "YAML_OR_JSON_MAPPING",
        "frontend_policy": "CONTROL_PANEL_KEY_FIELDS_ONLY",
        "detailed_config_file": detailed_config_file,
        "generated_config_file": generated_config_file,
        "template_config_file": view["template_config_file"],
        "template_profiles": configuration_template_profiles(),
        "template_validation": build_user_configuration_template_validation_evidence(),
        "unknown_key_policy": schema["unknown_key_policy"],
        "defaulting_policy": schema["defaulting_policy"],
        "mutation_policy": {
            "ui_surface": "KEY_FIELDS_ONLY",
            "full_file_surface": "DETAILED_CONFIG_FILE",
            "validate_endpoint": "POST /scenario/user-config/validate-text",
            "apply_commands": (
                "CONFIG_UPDATE",
                "LOAD_TEMPLATE",
                "RESTORE_EXPORT_PACKAGE",
            ),
        },
        "field_count": schema["field_count"],
        "key_field_count": view["key_field_count"],
        "file_only_field_count": len(view["file_only_fields"]),
        "section_count": len(sections),
        "sections": sections,
        "fields": tuple(_reference_field(field, key_field_set) for field in fields),
        "model_boundaries": {
            "event_kernel_policy": "NO_EVENT_KERNEL_BEHAVIOR_CHANGE",
            "packet_level_simulation": False,
            "external_simulators": False,
            "forbidden_integrations": ("STK", "EXATA", "AFSIM", "DDS"),
            "frontend_semantics_source": "BACKEND_USER_CONFIGURATION",
        },
        "operator_workflow": (
            "Use the control panel for key operational fields.",
            "Use the detailed YAML/JSON config file for full model inputs.",
            "Validate text with POST /scenario/user-config/validate-text before applying.",
            "Apply accepted templates with LOAD_TEMPLATE only before runtime start.",
            "Keep runtime-generated config snapshots out of source commits unless scoped.",
        ),
        "notes": (
            "This reference is derived from SEESConfig, user configuration schema v2, and the configuration surface summary.",
            "The frontend should display key fields first and link to this reference for advanced editing.",
            "All accepted values remain deterministic when runtime.seed and template version are fixed.",
        ),
    }
    reference["reference_hash"] = stable_hash_payload(reference)
    return reference


def _template_profile_by_id(template_id: str) -> Mapping[str, str]:
    for profile in _TEMPLATE_PROFILES:
        if profile["id"] == template_id:
            return profile
    known = ", ".join(str(profile["id"]) for profile in _TEMPLATE_PROFILES)
    raise ConfigValidationError(
        f"unknown configuration template_id: {template_id}; expected one of: {known}"
    )


def _template_validation_row(
    profile: Mapping[str, str],
    repository_root: Path,
) -> dict[str, object]:
    path = str(profile["path"])
    absolute_path = repository_root / path
    row: dict[str, object] = {
        "id": str(profile["id"]),
        "label": str(profile["label"]),
        "path": path,
        "scale": str(profile.get("scale", "")),
        "fidelity_mode": str(profile.get("fidelity_mode", "")),
        "expected_kpi_behavior": str(profile.get("expected_kpi_behavior", "")),
        "file_exists": absolute_path.is_file(),
        "file_hash": "",
        "config_hash": "",
        "load_ok": False,
        "validation_ok": False,
        "error_count": 0,
        "errors": (),
        "config_summary": {},
    }
    if not absolute_path.is_file():
        row.update(
            {
                "error_count": 1,
                "errors": (
                    {
                        "source": "template_file",
                        "message": f"template file is missing: {path}",
                    },
                ),
            }
        )
        row["row_hash"] = stable_hash_payload(row)
        return row
    row["file_hash"] = _file_sha256(absolute_path)
    try:
        config = load_config(absolute_path)
    except Exception as exc:  # pragma: no cover - covered by invalid template inputs.
        row.update(
            {
                "error_count": 1,
                "errors": (
                    {
                        "source": exc.__class__.__name__,
                        "message": str(exc),
                    },
                ),
            }
        )
        row["row_hash"] = stable_hash_payload(row)
        return row
    mapping = config_to_dict(config)
    validation = validate_user_configuration_mapping_v2(mapping)
    row.update(
        {
            "config_hash": stable_hash_payload(mapping),
            "load_ok": True,
            "validation_ok": bool(validation["ok"]),
            "error_count": int(validation["error_count"]),
            "errors": tuple(validation["errors"]),
            "config_summary": {
                "satellite_count": config.scenario.satellite_count,
                "user_count": config.scenario.user_count,
                "compute_nodes": config.scenario.compute_nodes,
                "traffic_class": _config_value(
                    config.scenario.traffic_model.traffic_class
                ),
                "destination_type": _config_value(
                    config.scenario.traffic_model.destination_type
                ),
                "runtime_mode": _config_value(config.runtime.mode),
                "runtime_duration": config.runtime.duration,
                "runtime_seed": config.runtime.seed,
                "orbit_update_mode": _config_value(
                    config.scenario.orbit.orbit_update_mode
                ),
                "space_link_mode": _config_value(config.network.space_link_mode),
            },
        }
    )
    row["row_hash"] = stable_hash_payload(row)
    return row


def _config_value(value: object) -> object:
    enum_value = getattr(value, "value", None)
    if isinstance(enum_value, str):
        return enum_value
    return value


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


def _reference_section(
    section: str,
    fields: tuple[Mapping[str, object], ...],
    key_field_set: frozenset[str],
) -> dict[str, object]:
    paths = tuple(
        str(field["path"])
        for field in fields
        if str(field["path"]) == section or str(field["path"]).startswith(f"{section}.")
    )
    key_paths = tuple(path for path in paths if path in key_field_set)
    file_only_paths = tuple(path for path in paths if path not in key_field_set)
    return {
        "section": section,
        "purpose": _SECTION_PURPOSES[section],
        "field_count": len(paths),
        "key_field_count": len(key_paths),
        "file_only_field_count": len(file_only_paths),
        "key_paths": key_paths,
        "file_only_paths": file_only_paths,
    }


def _reference_field(
    field: Mapping[str, object],
    key_field_set: frozenset[str],
) -> dict[str, object]:
    path = str(field["path"])
    result: dict[str, object] = {
        "path": path,
        "section": str(field["section"]),
        "label": str(field["label"]),
        "description": str(field["description"]),
        "value_type": str(field["value_type"]),
        "editable_surface": str(field["editable_surface"]),
        "ui_key_field": path in key_field_set,
        "default_value": field.get("default_value"),
        "current_value": field.get("current_value"),
        "required_in_user_file": bool(field.get("required_in_user_file")),
        "validation_rules": tuple(field.get("validation_rules", ())),
    }
    for optional_key in (
        "unit",
        "enum_values",
        "nullable",
        "minimum",
        "maximum",
        "exclusive_minimum",
        "exclusive_maximum",
    ):
        if optional_key in field:
            result[optional_key] = field[optional_key]
    return result


def _file_only_section_summaries(
    file_only_fields: tuple[str, ...],
) -> tuple[dict[str, object], ...]:
    by_section: dict[str, list[str]] = {
        section: [] for section in _SECTION_PURPOSES
    }
    for path in file_only_fields:
        by_section[_most_specific_section(path)].append(path)
    return tuple(
        {
            "section": section,
            "purpose": _SECTION_PURPOSES[section],
            "field_count": len(paths),
            "example_paths": tuple(paths[:6]),
        }
        for section, paths in sorted(by_section.items())
        if paths
    )


def _most_specific_section(path: str) -> str:
    candidates = tuple(
        section
        for section in _SECTION_PURPOSES
        if path == section or path.startswith(f"{section}.")
    )
    if not candidates:
        return path.split(".", maxsplit=1)[0]
    return max(candidates, key=len)


def _key_field(path: str, value: object) -> dict[str, object]:
    metadata = _FIELD_METADATA[path]
    field: dict[str, object] = {
        "path": path,
        "label": metadata["label"],
        "section": metadata["section"],
        "value": value,
        "role": metadata["role"],
        "editable_in_ui": True,
    }
    unit = metadata.get("unit")
    if unit is not None:
        field["unit"] = unit
    return field


def _section_summary(
    section: str,
    flattened: Mapping[str, object],
) -> dict[str, object]:
    paths = tuple(
        path
        for path in flattened
        if path == section or path.startswith(f"{section}.")
    )
    return {
        "section": section,
        "purpose": _SECTION_PURPOSES[section],
        "field_count": len(paths),
        "example_paths": paths[:6],
    }


def _flatten_paths(data: Mapping[str, Any]) -> dict[str, object]:
    flattened: dict[str, object] = {}

    def walk(prefix: str, value: object) -> None:
        if isinstance(value, Mapping):
            for key in sorted(value):
                child_path = f"{prefix}.{key}" if prefix else str(key)
                walk(child_path, value[key])
            return
        flattened[prefix] = value

    walk("", data)
    return dict(sorted(flattened.items()))
