"""Backend-owned user configuration surface summaries."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from leo_twin.schema.config import SEESConfig, config_to_dict


ConfigurationView = dict[str, object]

_KEY_FIELD_PATHS = (
    "scenario.satellite_count",
    "scenario.user_count",
    "scenario.compute_nodes",
    "scenario.compute_capacity",
    "scenario.compute_gpu_tflops_fp32",
    "scenario.compute_npu_tops_int8",
    "scenario.orbit.plane_count",
    "scenario.orbit.altitude_m",
    "scenario.orbit.inclination_deg",
    "scenario.traffic_model.traffic_class",
    "scenario.traffic_model.flow_interval_seconds",
    "scenario.traffic_model.flow_demand_capacity",
    "scenario.traffic_model.task_compute_demand",
    "network.transport_protocol",
    "network.transport_loss_rate",
    "network.space_link_mode",
    "runtime.mode",
    "runtime.speed_factor",
    "runtime.duration",
)

_FIELD_METADATA: Mapping[str, Mapping[str, str]] = {
    "scenario.satellite_count": {
        "label": "Satellite count",
        "section": "Scenario scale",
        "role": "Primary constellation size selected by the user.",
    },
    "scenario.user_count": {
        "label": "User node count",
        "section": "Scenario scale",
        "role": "Number of generated user terminals.",
    },
    "scenario.compute_nodes": {
        "label": "Compute satellite count",
        "section": "Scenario scale",
        "role": "Satellites that host compute resources.",
    },
    "scenario.compute_capacity": {
        "label": "CPU FP32 per compute satellite",
        "section": "Compute resources",
        "role": "Legacy scalar capacity mapped to FP32 GFLOPS.",
        "unit": "GFLOPS",
    },
    "scenario.compute_gpu_tflops_fp32": {
        "label": "GPU FP32 per compute satellite",
        "section": "Compute resources",
        "role": "Optional accelerator capacity.",
        "unit": "TFLOPS",
    },
    "scenario.compute_npu_tops_int8": {
        "label": "NPU INT8 per compute satellite",
        "section": "Compute resources",
        "role": "Optional inference accelerator capacity.",
        "unit": "TOPS",
    },
    "scenario.orbit.plane_count": {
        "label": "Orbit plane count",
        "section": "Orbit",
        "role": "Walker-like deterministic plane allocation input.",
    },
    "scenario.orbit.altitude_m": {
        "label": "Orbit altitude",
        "section": "Orbit",
        "role": "Simplified circular orbit altitude.",
        "unit": "m",
    },
    "scenario.orbit.inclination_deg": {
        "label": "Inclination",
        "section": "Orbit",
        "role": "Simplified orbit inclination.",
        "unit": "deg",
    },
    "scenario.traffic_model.traffic_class": {
        "label": "Traffic class",
        "section": "Traffic demand",
        "role": "Flow-level demand class generated by the backend.",
    },
    "scenario.traffic_model.flow_interval_seconds": {
        "label": "Flow arrival interval",
        "section": "Traffic demand",
        "role": "Deterministic interval between generated flow arrivals.",
        "unit": "s",
    },
    "scenario.traffic_model.flow_demand_capacity": {
        "label": "Flow demand",
        "section": "Traffic demand",
        "role": "Requested flow capacity.",
        "unit": "Mbps",
    },
    "scenario.traffic_model.task_compute_demand": {
        "label": "Task compute demand",
        "section": "Traffic demand",
        "role": "Abstract compute demand for compute-service tasks.",
    },
    "network.transport_protocol": {
        "label": "Transport protocol",
        "section": "Network",
        "role": "Flow-level transport profile.",
    },
    "network.transport_loss_rate": {
        "label": "Transport loss rate",
        "section": "Network",
        "role": "Deterministic loss proxy input, not packet loss simulation.",
    },
    "network.space_link_mode": {
        "label": "Space-space link mode",
        "section": "Network",
        "role": "Selected ISL fidelity mode.",
    },
    "runtime.mode": {
        "label": "Runtime mode",
        "section": "Runtime",
        "role": "Execution mode selected before start.",
    },
    "runtime.speed_factor": {
        "label": "Runtime speed",
        "section": "Runtime",
        "role": "Acceleration factor, locked while running.",
    },
    "runtime.duration": {
        "label": "Simulation duration",
        "section": "Runtime",
        "role": "Configured terminal simulation time.",
        "unit": "s",
    },
}

_SECTION_PURPOSES = {
    "scenario": "Constellation scale, compute resource, workload, orbit, and traffic demand.",
    "scenario.orbit": "Deterministic orbit allocation and update cadence.",
    "scenario.traffic_model": "Flow-level user business generation model.",
    "network": "Flow-level protocol, link budget, routing, and ISL fidelity inputs.",
    "runtime": "Execution mode, speed, seed, and duration.",
    "ui": "Frontend visualization preferences.",
    "ui.visualization": "Layer visibility defaults.",
}


def build_user_configuration_view(config: SEESConfig) -> ConfigurationView:
    """Return a deterministic user-facing config surface contract."""

    if not isinstance(config, SEESConfig):
        raise TypeError("config must be SEESConfig")
    data = config_to_dict(config)
    flattened = _flatten_paths(data)
    key_paths = tuple(path for path in _KEY_FIELD_PATHS if path in flattened)
    key_path_set = frozenset(key_paths)
    file_only_fields = tuple(path for path in flattened if path not in key_path_set)
    return {
        "version": "v1",
        "source": "backend_sees_config",
        "detailed_config_file": "configs/sees_control.yaml",
        "template_config_file": "configs/templates/sees_user_detailed.example.yaml",
        "frontend_policy": "CONTROL_PANEL_KEY_FIELDS_ONLY",
        "key_field_count": len(key_paths),
        "detailed_field_count": len(flattened),
        "key_fields": tuple(
            _key_field(path, flattened[path])
            for path in key_paths
        ),
        "detailed_file_sections": tuple(
            _section_summary(section, flattened)
            for section in sorted(_SECTION_PURPOSES)
        ),
        "file_only_fields": file_only_fields,
        "notes": (
            "The control panel should expose key_fields for common operation.",
            "Advanced users should edit the detailed config file or template for full control.",
            "This summary is derived from SEESConfig and is the backend source of truth.",
        ),
    }


def _key_field(path: str, value: object) -> dict[str, object]:
    metadata = _FIELD_METADATA[path]
    field: dict[str, object] = {
        "path": path,
        "label": metadata["label"],
        "section": metadata["section"],
        "value": value,
        "role": metadata["role"],
        "editable_in_ui": True,
    }
    unit = metadata.get("unit")
    if unit is not None:
        field["unit"] = unit
    return field


def _section_summary(
    section: str,
    flattened: Mapping[str, object],
) -> dict[str, object]:
    paths = tuple(
        path
        for path in flattened
        if path == section or path.startswith(f"{section}.")
    )
    return {
        "section": section,
        "purpose": _SECTION_PURPOSES[section],
        "field_count": len(paths),
        "example_paths": paths[:6],
    }


def _flatten_paths(data: Mapping[str, Any]) -> dict[str, object]:
    flattened: dict[str, object] = {}

    def walk(prefix: str, value: object) -> None:
        if isinstance(value, Mapping):
            for key in sorted(value):
                child_path = f"{prefix}.{key}" if prefix else str(key)
                walk(child_path, value[key])
            return
        flattened[prefix] = value

    walk("", data)
    return dict(sorted(flattened.items()))
