"""Frozen cross-module domain data schemas."""

from dataclasses import dataclass
from math import isfinite
from typing import Any


@dataclass(frozen=True)
class SatelliteState:
    """State published by the orbit module."""

    satellite_id: str
    sim_time: float
    position: tuple[float, float, float]
    velocity: tuple[float, float, float]
    status: str

    def __post_init__(self) -> None:
        _require_non_empty_str(self.satellite_id, "satellite_id")
        _require_finite_number(self.sim_time, "sim_time")
        _require_vector3(self.position, "position")
        _require_vector3(self.velocity, "velocity")
        _require_non_empty_str(self.status, "status")


@dataclass(frozen=True)
class AccessAssociation:
    """Satellite-ground association output by the network module."""

    satellite_id: str
    user_id: str

    def __post_init__(self) -> None:
        _require_non_empty_str(self.satellite_id, "satellite_id")
        _require_non_empty_str(self.user_id, "user_id")


@dataclass(frozen=True)
class FlowState:
    """Flow state consumed by compute and metrics modules."""

    flow_id: str
    route_id: str
    source_id: str
    target_id: str
    status: str

    def __post_init__(self) -> None:
        _require_non_empty_str(self.flow_id, "flow_id")
        _require_non_empty_str(self.route_id, "route_id")
        _require_non_empty_str(self.source_id, "source_id")
        _require_non_empty_str(self.target_id, "target_id")
        _require_non_empty_str(self.status, "status")


@dataclass(frozen=True)
class ComputeNodeState:
    """Compute node state published by the compute module."""

    node_id: str
    sim_time: float
    capacity: float
    available_capacity: float
    status: str

    def __post_init__(self) -> None:
        _require_non_empty_str(self.node_id, "node_id")
        _require_finite_number(self.sim_time, "sim_time")
        _require_non_negative_number(self.capacity, "capacity")
        _require_non_negative_number(self.available_capacity, "available_capacity")
        _require_non_empty_str(self.status, "status")


@dataclass(frozen=True)
class TaskRequest:
    """Compute task request consumed by the compute module."""

    task_id: str
    source_id: str
    submit_time: float
    compute_demand: float
    data_size: float
    deadline: float | None = None

    def __post_init__(self) -> None:
        _require_non_empty_str(self.task_id, "task_id")
        _require_non_empty_str(self.source_id, "source_id")
        _require_finite_number(self.submit_time, "submit_time")
        _require_non_negative_number(self.compute_demand, "compute_demand")
        _require_non_negative_number(self.data_size, "data_size")
        if self.deadline is not None:
            _require_finite_number(self.deadline, "deadline")


@dataclass(frozen=True)
class TaskState:
    """Task state output by the compute module."""

    task_id: str
    node_id: str
    sim_time: float
    progress: float
    status: str

    def __post_init__(self) -> None:
        _require_non_empty_str(self.task_id, "task_id")
        _require_non_empty_str(self.node_id, "node_id")
        _require_finite_number(self.sim_time, "sim_time")
        _require_non_negative_number(self.progress, "progress")
        _require_non_empty_str(self.status, "status")


@dataclass(frozen=True)
class MetricRecord:
    """Metric sample generated by the metrics module."""

    metric_name: str
    sim_time: float
    entity_id: str
    value: float | str | bool
    tags: tuple[tuple[str, str], ...] = ()

    def __post_init__(self) -> None:
        _require_non_empty_str(self.metric_name, "metric_name")
        _require_finite_number(self.sim_time, "sim_time")
        _require_non_empty_str(self.entity_id, "entity_id")
        normalized_tags = tuple(sorted((str(key), str(value)) for key, value in self.tags))
        object.__setattr__(self, "tags", normalized_tags)


def _require_non_empty_str(value: str, field_name: str) -> None:
    if not isinstance(value, str) or not value:
        raise TypeError(f"{field_name} must be a non-empty str")


def _require_finite_number(value: Any, field_name: str) -> None:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"{field_name} must be an int or float")
    if not isfinite(value):
        raise ValueError(f"{field_name} must be finite")


def _require_non_negative_number(value: Any, field_name: str) -> None:
    _require_finite_number(value, field_name)
    if value < 0:
        raise ValueError(f"{field_name} must be non-negative")


def _require_vector3(value: Any, field_name: str) -> None:
    if not isinstance(value, tuple) or len(value) != 3:
        raise TypeError(f"{field_name} must be a 3-tuple")
    for item in value:
        _require_finite_number(item, field_name)
