from leo_twin.sees.codex_executor import FilePatch
from leo_twin.sees.runner import SEESRunner
from leo_twin.sees.task_dag import TASK_COMPLETE, EngineeringTask, TaskDAG


def test_full_sees_loop_executes_reviews_gates_and_generates_next_task(
    valid_review_workspace,
):
    task = EngineeringTask(
        task_id="task-sees-001",
        title="Add deterministic generated service marker",
        description="A deterministic patch generated by the executor.",
        issue_id="SEES-001",
        patch_plan=(
            FilePatch(
                path="src/leo_twin/services/generated_marker.py",
                content=(
                    "def generated_marker() -> str:\n"
                    "    return \"ok\"\n"
                ),
            ),
        ),
    )
    dag = TaskDAG((task,))

    result = SEESRunner().run_once(dag, valid_review_workspace)

    assert result.ci_exit_code == 0
    assert result.final_report["decision"] == "PASS"
    assert dag.get_task("task-sees-001").status == TASK_COMPLETE
    assert result.generated_tasks
    assert (valid_review_workspace / "src/leo_twin/services/generated_marker.py").exists()
